version: '3.8'
services:
  reporter:
    volumes:
      - /home/alex/projects/wer/:/reporter/audio/wer      
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    build: reporter
    environment:
      - VOSK_SERVER_DEFAULT=ws://10.2.4.87:2700
      - TELEGRAM_CHAT=-1001443983697
      - TELEGRAM_BOT_TOKEN=